print("\033[1mExercici1\033[0m")
print("1","2","3","4","5","++", sep="---")
input("Pulsa una tecla para ver el Exercici 2:")
print("\033[1mExercici 2\033[0m")
print('"Estoy"')
print("======================")
print('\"Algunos simbolos\"')
print("======================")
print("''Son difíciles de imprimir: '/'\" ''")
print("======================")
print("I'm a programmer!!")
input("Pulsa una tecla para ver el Exercici 3:")
print("\033[1mExercici 3\033[0m]")
print("'I'm Monty Python.'")
input("Pulsa una tecla para ver el Exercici 4:")
print("\033[1mExercici 4\033[0m")
x=(((3+2) / (2*5))**2)
print(x)